### ISSUE TITLE
AttributeError: module 'mujoco' has no attribute 'viewer'

### ISSUE THREAD

**Issue by zichunxx** [kevinzakka/mjctrl#1]
Hi! 

The absence of `import mujoco.viewer` will trigger the following error:

```
    with mujoco.viewer.launch_passive(
AttributeError: module 'mujoco' has no attribute 'viewer'
```

**Comment by kevinzakka** [comment]
Hi @zichunxx, this repo is still a work in progress, I should add a disclaimer. Regarding the error, it runs fine for me on mac without the import. Is this on linux?

**Comment by zichunxx** [comment]
Yeah, I met this error on Linux Ubuntu.

**Comment by kevinzakka** [comment]
Should be fixed now.
