### ISSUE TITLE
Getting error when using the codebase for XArm 7

### ISSUE THREAD

**Issue by shivanshpatel35** [kevinzakka/mjctrl#6]
Hi,
I am trying to use your codebase to control XArm robot. Its XML is [here](https://github.com/google-deepmind/mujoco_menagerie/blob/main/ufactory_xarm7/xarm7_nohand.xml). When I run `diffik_nullspace.py` after changing the path to XArm7 [here](https://github.com/kevinzakka/mjctrl/blob/main/diffik_nullspace.py#L36), I get the error [here](https://github.com/kevinzakka/mjctrl/blob/main/diffik_nullspace.py#L114). 
```
operands could not be broadcast together with shapes (13,) (7,) 
```
There are few discrepancies that I noticed:
1. jac = np.zeros((6, model.nv)) [here](https://github.com/kevinzakka/mjctrl/blob/main/diffik_nullspace.py#L72). My model.nv is 13. I guess it should be rather 7 (== degree of freedom).
2. q0 = model.key(key_name).qpos [here](https://github.com/kevinzakka/mjctrl/blob/main/diffik_nullspace.py#L65). q0's shape is (13,) even though I feel it should be [(7,)](https://github.com/google-deepmind/mujoco_menagerie/blob/main/ufactory_xarm7/xarm7_nohand.xml#L104). 

Am I interpreting anything wrong?

**Comment by kevinzakka** [comment]
Are you using the xarm with the gripper? If so, you need to mask out the dofs corresponding to the gripper and make sure you index correctly into the different matrices. I’ll let you give it a go, if you get stuck, come back and let me know and I can give some pointers.

**Comment by shivanshpatel35** [comment]
Just indexing the matrices [here](https://github.com/kevinzakka/mjctrl/blob/main/diffik_nullspace.py#L114) made it work for XArm7 with gripper. 

Thanks a lot, Kevin!

**Comment by jonzamora** [comment]
Update: I was running into an issue like this, and indexing the matrices was all i needed to do as well
